requirements.txt: Updated python version >=3.9, <3.12
kokkos/pykokkos-base pull request #59
Opened 2024-01-18 18:32 UTC by HannanNaeem

Explicitly adding supported python versions in requirements.txt, as the setup or pykokkos is currently incompatible outside this range. 

Previously the environment defaulted to the latest python package (at this time 3.12.x), which is not supported.

2024-01-18 18:40 UTC, jrmadsen commented
If there’s a problem with Python 3.12, that probably just means the [pybind11 submodule](https://github.com/kokkos/pykokkos-base/tree/main/external) needs to be updated, bc it looks like it hasn’t been updated in 2 years

2024-01-18 19:08 UTC, HannanNaeem commented
I will check it out, thanks!

2024-01-19 16:25 UTC, NaderAlAwar requested changes
There are also CI failures you should look into

2024-01-19 16:25 UTC, NaderAlAwar commented on requirements.txt
> +python>3.9,<3.12
This is incorrect, should be >= 3.9

2024-05-18 05:21 UTC, closed without merging